version: '3.8'
services:
  app:
    container_name: whoami-frontend
    build:
      context: .
      target: production
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - whoamitoday-network
    restart: unless-stopped

networks:
  whoamitoday-network:
    external: true