const MAX_WINDOW_WIDTH = 500;
const BOTTOM_TABBAR_HEIGHT = 80;
const TOP_NAVIGATION_HEIGHT = 44;
const BOTTOMSHEET_HEADER_HEIGHT = 85;
const DEFAULT_MARGIN = 16;
const SCREEN_WIDTH = typeof window !== 'undefined' ? Math.min(window.innerWidth, 500) : 0;
const SCREEN_HEIGHT = typeof window !== 'undefined' ? window.innerHeight : 0;
const TITLE_HEADER_HEIGHT = 44;
const PING_MESSAGE_INPUT_HEIGHT = 65;
const PING_EMOJI_AREA_SIZE = 30;
const PING_EMOJI_FONT_SIZE = 22;

const EMOJI_PICKER_HEIGHT = {
  DEFAULT: 200,
  SHORT: 150,
};

const Z_INDEX = {
  TITLE_HEADER: 100,
  NOTI_PERMISSION_BANNER: 200,
  MODAL_CONTAINER: 1000,
  TOAST_CONTAINER: 2000,
  BOTTOM_TAB: 300,
  EMOJI_PICKER: 20,
  COMMENT_LIKES_POPUP: 1500,
};

export {
  BOTTOM_TABBAR_HEIGHT,
  BOTTOMSHEET_HEADER_HEIGHT,
  DEFAULT_MARGIN,
  EMOJI_PICKER_HEIGHT,
  MAX_WINDOW_WIDTH,
  PING_EMOJI_AREA_SIZE,
  PING_EMOJI_FONT_SIZE,
  PING_MESSAGE_INPUT_HEIGHT,
  SCREEN_HEIGHT,
  SCREEN_WIDTH,
  TITLE_HEADER_HEIGHT,
  TOP_NAVIGATION_HEIGHT,
  Z_INDEX,
};
